name: Generate Realm Android Signing Key

on:
  workflow_dispatch:

jobs:
  generate-key:
    runs-on: ubuntu-24.04

    steps:
      - name: Generate Realm of Kings signing key
        shell: bash
        env:
          JKS_PASS: ${{ secrets.REALM_JKS_PASS }}
        run: |
          keytool -genkeypair \
            -v \
            -keystore realm-of-kings.jks \
            -storepass "$JKS_PASS" \
            -keypass "$JKS_PASS" \
            -alias realm-of-kings \
            -keyalg RSA \
            -keysize 4096 \
            -validity 10000 \
            -dname "CN=Realm of Kings, OU=Realm of Kings, O=Realm of Kings, L=Nassau, ST=New Providence, C=BS"

          echo "Realm of Kings signing key generated successfully."

      - name: Upload signing key
        uses: actions/upload-artifact@v4
        with:
          name: realm-of-kings-android-signing-key
          path: realm-of-kings.jks
          retention-days: 1
